export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const INCREASE_ORDER = "INCREASE_ORDER";
export const DECREASE_ORDER = "DECREASE_ORDER";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_CART = "CLEAR_CART";
